keys:
  - &personal age1t5wqlyhh2ft93gwhuxvwxhw6j0pq0xzaek4445dw5z7r9265zv5qrdaws7
creation_rules:
  - path_regex: global/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *personal